"""create initial tables

Revision ID: 119c0361d3ed
Revises: 
Create Date: 2023-06-01 16:31:29.166062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119c0361d3ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_type',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_index(op.f('ix_data_type_type_id'), 'data_type', ['type_id'], unique=False)
    op.create_table('membership',
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('membership_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('membership_id')
    )
    op.create_index(op.f('ix_membership_membership_id'), 'membership', ['membership_id'], unique=False)
    op.create_table('project_type',
    sa.Column('project_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=32), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('project_type_id')
    )
    op.create_index(op.f('ix_project_type_project_type_id'), 'project_type', ['project_type_id'], unique=False)
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=32), nullable=True),
    sa.Column('role_desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_role_role_id'), 'role', ['role_id'], unique=False)
    op.create_table('social_platform_type',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_index(op.f('ix_social_platform_type_provider_id'), 'social_platform_type', ['provider_id'], unique=False)
    op.create_table('system_info',
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.String(length=512), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_index(op.f('ix_system_info_version'), 'system_info', ['version'], unique=False)
    op.create_table('team',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=32), nullable=True),
    sa.Column('team_info', sa.String(length=32), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index(op.f('ix_team_team_id'), 'team', ['team_id'], unique=False)
    op.create_table('user_type',
    sa.Column('user_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('user_type_id')
    )
    op.create_index(op.f('ix_user_type_user_type_id'), 'user_type', ['user_type_id'], unique=False)
    op.create_table('project',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_type', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=32), nullable=True),
    sa.Column('data_type', sa.Integer(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_type'], ['data_type.type_id'], ),
    sa.ForeignKeyConstraint(['project_type'], ['project_type.project_type_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_project_project_id'), 'project', ['project_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=False),
    sa.Column('user_pw', sa.String(length=128), nullable=True),
    sa.Column('social_id', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['membership_id'], ['membership.membership_id'], ),
    sa.ForeignKeyConstraint(['provider'], ['social_platform_type.provider_id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_type.user_type_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'email'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('organization',
    sa.Column('org_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_email', sa.String(length=128), nullable=False),
    sa.Column('org_name', sa.String(length=32), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_index(op.f('ix_organization_org_id'), 'organization', ['org_id'], unique=False)
    op.create_table('team_projects',
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], onupdate='CASCADE', ondelete='CASCADE')
    )
    op.create_table('user_project_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE')
    )
    op.create_table('user_teams',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE')
    )
    op.create_table('user_organization',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE')
    )
    op.create_table('workspace',
    sa.Column('workspace_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('workspace_name', sa.String(length=32), nullable=True),
    sa.Column('workspace_info', sa.String(length=128), nullable=True),
    sa.Column('invitation_link', sa.String(length=128), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_index(op.f('ix_workspace_workspace_id'), 'workspace', ['workspace_id'], unique=False)
    op.create_table('workspace_teams',
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], onupdate='CASCADE', ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_teams')
    op.drop_index(op.f('ix_workspace_workspace_id'), table_name='workspace')
    op.drop_table('workspace')
    op.drop_table('user_organization')
    op.drop_table('user_teams')
    op.drop_table('user_project_roles')
    op.drop_table('team_projects')
    op.drop_index(op.f('ix_organization_org_id'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_project_project_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_user_type_user_type_id'), table_name='user_type')
    op.drop_table('user_type')
    op.drop_index(op.f('ix_team_team_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_system_info_version'), table_name='system_info')
    op.drop_table('system_info')
    op.drop_index(op.f('ix_social_platform_type_provider_id'), table_name='social_platform_type')
    op.drop_table('social_platform_type')
    op.drop_index(op.f('ix_role_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_project_type_project_type_id'), table_name='project_type')
    op.drop_table('project_type')
    op.drop_index(op.f('ix_membership_membership_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_data_type_type_id'), table_name='data_type')
    op.drop_table('data_type')
    # ### end Alembic commands ###
