"""add profile_image column to user table

Revision ID: 29144b22d578
Revises: ea1835779a3a
Create Date: 2023-06-21 09:57:05.360410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29144b22d578'
down_revision = 'ea1835779a3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image')
    # ### end Alembic commands ###
