"""add cascade options to tables

Revision ID: 2c1b838b8ebe
Revises: d4294ba4e064
Create Date: 2023-06-01 11:26:19.174229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1b838b8ebe'
down_revision = 'd4294ba4e064'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'organization', 'user', ['creator_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('team_projects_ibfk_1', 'team_projects', type_='foreignkey')
    op.drop_constraint('team_projects_ibfk_2', 'team_projects', type_='foreignkey')
    op.create_foreign_key(None, 'team_projects', 'team', ['team_id'], ['team_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'team_projects', 'project', ['project_id'], ['project_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('user_organization_ibfk_1', 'user_organization', type_='foreignkey')
    op.drop_constraint('user_organization_ibfk_2', 'user_organization', type_='foreignkey')
    op.create_foreign_key(None, 'user_organization', 'organization', ['org_id'], ['org_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_organization', 'user', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('user_project_roles_ibfk_3', 'user_project_roles', type_='foreignkey')
    op.drop_constraint('user_project_roles_ibfk_1', 'user_project_roles', type_='foreignkey')
    op.drop_constraint('user_project_roles_ibfk_2', 'user_project_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_project_roles', 'project', ['project_id'], ['project_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_project_roles', 'role', ['role_id'], ['role_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_project_roles', 'user', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('user_teams_ibfk_1', 'user_teams', type_='foreignkey')
    op.drop_constraint('user_teams_ibfk_2', 'user_teams', type_='foreignkey')
    op.create_foreign_key(None, 'user_teams', 'user', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_teams', 'team', ['team_id'], ['team_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'workspace', 'user', ['creator_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'workspace', 'organization', ['org_id'], ['org_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('workspace_teams_ibfk_1', 'workspace_teams', type_='foreignkey')
    op.drop_constraint('workspace_teams_ibfk_2', 'workspace_teams', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_teams', 'workspace', ['workspace_id'], ['workspace_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'workspace_teams', 'team', ['team_id'], ['team_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_teams', type_='foreignkey')
    op.drop_constraint(None, 'workspace_teams', type_='foreignkey')
    op.create_foreign_key('workspace_teams_ibfk_2', 'workspace_teams', 'workspace', ['workspace_id'], ['workspace_id'])
    op.create_foreign_key('workspace_teams_ibfk_1', 'workspace_teams', 'team', ['team_id'], ['team_id'])
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.drop_constraint(None, 'user_teams', type_='foreignkey')
    op.drop_constraint(None, 'user_teams', type_='foreignkey')
    op.create_foreign_key('user_teams_ibfk_2', 'user_teams', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('user_teams_ibfk_1', 'user_teams', 'team', ['team_id'], ['team_id'])
    op.drop_constraint(None, 'user_project_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_project_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_project_roles', type_='foreignkey')
    op.create_foreign_key('user_project_roles_ibfk_2', 'user_project_roles', 'role', ['role_id'], ['role_id'])
    op.create_foreign_key('user_project_roles_ibfk_1', 'user_project_roles', 'project', ['project_id'], ['project_id'])
    op.create_foreign_key('user_project_roles_ibfk_3', 'user_project_roles', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'user_organization', type_='foreignkey')
    op.drop_constraint(None, 'user_organization', type_='foreignkey')
    op.create_foreign_key('user_organization_ibfk_2', 'user_organization', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('user_organization_ibfk_1', 'user_organization', 'organization', ['org_id'], ['org_id'])
    op.drop_constraint(None, 'team_projects', type_='foreignkey')
    op.drop_constraint(None, 'team_projects', type_='foreignkey')
    op.create_foreign_key('team_projects_ibfk_2', 'team_projects', 'team', ['team_id'], ['team_id'])
    op.create_foreign_key('team_projects_ibfk_1', 'team_projects', 'project', ['project_id'], ['project_id'])
    op.drop_constraint(None, 'organization', type_='foreignkey')
    # ### end Alembic commands ###
