"""add col to project table

Revision ID: 834a6a0ea0ec
Revises: 06d9fb63383d
Create Date: 2023-08-23 09:37:55.098260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '834a6a0ea0ec'
down_revision = '06d9fb63383d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_workspace',
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], onupdate='CASCADE', ondelete='CASCADE')
    )
    op.add_column('project', sa.Column('project_preproccess', sa.Boolean(), nullable=False))
    op.add_column('project', sa.Column('preproccess_tags', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('project_classes', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('project_task_type', sa.String(length=32), nullable=False))
    op.alter_column('project', 'project_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'project_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=True)
    op.drop_column('project', 'project_task_type')
    op.drop_column('project', 'project_classes')
    op.drop_column('project', 'preproccess_tags')
    op.drop_column('project', 'project_preproccess')
    op.drop_table('project_workspace')
    # ### end Alembic commands ###
