"""delete project task type col

Revision ID: 921fc5dce903
Revises: 8a8fa200c36b
Create Date: 2023-08-23 10:50:57.103138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '921fc5dce903'
down_revision = '8a8fa200c36b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_task_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_task_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False))
    # ### end Alembic commands ###
