"""create workspace_type table and add workspace_type_id column to workspace table

Revision ID: ea1835779a3a
Revises: 339286e32cb6
Create Date: 2023-06-19 13:50:23.515220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1835779a3a'
down_revision = '339286e32cb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_type',
    sa.Column('workspace_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('workspace_type_id')
    )
    op.create_index(op.f('ix_workspace_type_workspace_type_id'), 'workspace_type', ['workspace_type_id'], unique=False)
    op.add_column('workspace', sa.Column('workspace_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workspace', 'workspace_type', ['workspace_type_id'], ['workspace_type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.drop_column('workspace', 'workspace_type_id')
    op.drop_index(op.f('ix_workspace_type_workspace_type_id'), table_name='workspace_type')
    op.drop_table('workspace_type')
    # ### end Alembic commands ###
