"""fix relationships

Revision ID: ec7d30826fae
Revises: ad7377c36044
Create Date: 2023-06-13 08:26:13.388201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7d30826fae'
down_revision = 'ad7377c36044'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
