"""add creator_id to project table

Revision ID: ff73f686082b
Revises: 921fc5dce903
Create Date: 2023-08-29 08:03:30.634645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff73f686082b'
down_revision = '921fc5dce903'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'user', ['creator_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'creator_id')
    # ### end Alembic commands ###
