version: '3.3'
  
services:

  diva-db-server-1:
    image: mysql:8
    command:
        - --default-authentication-plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
    restart: always
    container_name : diva-db-server-1
    environment:
      MYSQL_ROOT_PASSWORD: diva1234
      LANG: C.utf8
      TZ: "Asia/Seoul"
    volumes:
      - ./master_data:/var/lib/mysql
      - ./master.cnf:/etc/mysql/conf.d/master.cnf
    ports:
      - 1306:3306


  diva-db-server-2:
    image: mysql:8
    command:
        - --default-authentication-plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
    restart: always
    container_name : diva-db-server-2
    environment:
      MYSQL_ROOT_PASSWORD: diva1234
      LANG: C.utf8
      TZ: "Asia/Seoul"
    volumes:
      - ./slave_data:/var/lib/mysql
      - ./slave.cnf:/etc/mysql/conf.d/master.cnf
    ports:
      - 2306:3306
