version: '3.8'
services:
  mongo1:
    image: mongo
    container_name: dva-mongo1
    restart: always
    ports:
      - 8833:27017
    command: --replSet my-mongo-set

  mongo2:
    image: mongo
    container_name: dva-mongo2
    restart: always
    command: --replSet my-mongo-set

  mongo3:
    image: mongo
    container_name: dva-mongo3
    restart: always
    command: --replSet my-mongo-set